///////////////////////////////////////////////////////////
//  Automaton.cs
//  Implementation of the Class Automaton
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




using characters.soldiers;
namespace characters.soldiers {
	public class Automaton : Soldier {

		public Automaton(){

		}

		~Automaton(){

		}

		public override void Dispose(){

		}

	}//end Automaton

}//end namespace soldiers