///////////////////////////////////////////////////////////
//  Soldier.cs
//  Implementation of the Class Soldier
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




using characters;
using props.guns;
using props.tools;
namespace characters.soldiers {
	public class Soldier : Person {

		public props.guns.Gun m_Gun;
		public props.tools.Tool m_Tool;

		public Soldier(){

		}

		~Soldier(){

		}

		public override void Dispose(){

		}

	}//end Soldier

}//end namespace soldiers