///////////////////////////////////////////////////////////
//  Command.cs
//  Implementation of the Class Command
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




using characters.soldiers.team;
namespace characters.soldiers.team.commands {
	public class Command {

		public characters.soldiers.team.FireTeam m_FireTeam;

		public Command(){

		}

		~Command(){

		}

		public virtual void Dispose(){

		}

	}//end Command

}//end namespace commands