///////////////////////////////////////////////////////////
//  FireTeam.cs
//  Implementation of the Class FireTeam
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




using characters.soldiers;
using characters.soldiers.team;
namespace characters.soldiers.team {
	public class FireTeam : MonoBehaviour {

		public characters.soldiers.Soldier m_Soldier;
		public GunUse m_GunUse;
		public characters.soldiers.team.Point m_Point;

		public FireTeam(){

		}

		~FireTeam(){

		}

		public override void Dispose(){

		}

	}//end FireTeam

}//end namespace team