///////////////////////////////////////////////////////////
//  Point.cs
//  Implementation of the Class Point
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




using characters.soldiers.team.commands;
namespace characters.soldiers.team {
	public class Point : MonoBehaviour {

		public characters.soldiers.team.commands.Command m_Command;

		public Point(){

		}

		~Point(){

		}

		public override void Dispose(){

		}

	}//end Point

}//end namespace team