///////////////////////////////////////////////////////////
//  GunUse.cs
//  Implementation of the Class GunUse
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




public class GunUse {

	public GunUse(){

	}

	~GunUse(){

	}

	public virtual void Dispose(){

	}

}//end GunUse