///////////////////////////////////////////////////////////
//  Gun.cs
//  Implementation of the Class Gun
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




namespace props.guns {
	public class Gun {

		public Gun(){

		}

		~Gun(){

		}

		public virtual void Dispose(){

		}

	}//end Gun

}//end namespace guns