///////////////////////////////////////////////////////////
//  Tool.cs
//  Implementation of the Interface Tool
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




namespace props.tools {
	public interface Tool  {

	}//end Tool

}//end namespace tools