///////////////////////////////////////////////////////////
//  Formation.cs
//  Implementation of the Class Formation
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




using characters.soldiers.team;
namespace characters.soldiers.team.formations {
	public class Formation {

		public characters.soldiers.team.FireTeam m_FireTeam;

		public Formation(){

		}

		~Formation(){

		}

		public virtual void Dispose(){

		}

	}//end Formation

}//end namespace formations