///////////////////////////////////////////////////////////
//  Hostage.cs
//  Implementation of the Class Hostage
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




using characters;
namespace characters {
	public class Hostage : Person {

		public Hostage(){

		}

		~Hostage(){

		}

		public override void Dispose(){

		}

	}//end Hostage

}//end namespace characters