///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




namespace characters {
	public class Person : MonoBehaviour {

		public Person(){

		}

		~Person(){

		}

		public override void Dispose(){

		}

	}//end Person

}//end namespace characters