///////////////////////////////////////////////////////////
//  Level.cs
//  Implementation of the Class Level
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:05 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




namespace ctrl {
	public class Level : MonoBehaviour {

		public Level(){

		}

		~Level(){

		}

		public override void Dispose(){

		}

	}//end Level

}//end namespace ctrl