///////////////////////////////////////////////////////////
//  Objective.cs
//  Implementation of the Class Objective
//  Generated by Enterprise Architect
//  Created on:      01-jul-2013 08:32:23 p.m.
//  Original author: Camilo
///////////////////////////////////////////////////////////




namespace ctrl {
	public class Objective : MonoBehaviour {

		public Objective(){

		}

		~Objective(){

		}

		public override void Dispose(){

		}

	}//end Objective

}//end namespace ctrl